model:
  in_feat: 66
  hid_feat: 32

dataset:
  root_dir: 'data/sequences'
  prefix: pls_cylindrical_mt
  spatial_shape: [480,360,32]
  max_bound: [50,3.1415926,2]
  min_bound: [0,-3.1415926,-4]
  aug:
    student: ['rotate', 'flip', 'scale', 'noise']
    teacher: ['rotate', 'flip']
  bin_size: [[24,9],[48,18],[96,36]]

train_dataloader:
  batch_size: 1
  shuffle: True
  num_workers: 4

val_dataloader:
  batch_size: 1
  shuffle: False
  num_workers: 4

trainer:
  max_epochs: 75
  gpus: -1
  check_val_every_n_epoch: 1
  default_root_dir: 'output'
  accelerator: 'ddp'
  sync_batchnorm: True
  accumulate_grad_batches: 2
  num_sanity_val_steps: 1

optimizer:
  lr: 0.001

logger:
  project: 'scribblekitti'
  name: 'training'
